name: Build Life Map

on:
  push:
    branches: [ main ]
    paths:
      - 'logs/**'
      - 'scripts/**'
      - 'README.md'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Update Life Map section
        run: |
          python scripts/build_map.py
      - name: Commit changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(life-map): auto-update graph"
            git push
          else
            echo "No changes to commit"
          fi
